baseURL = 'https://example.org/'
languageCode = 'en-us'
defaultContentLanguage = 'en-us'
title = 'minimal'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

# Default config
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'TIL'
pageRef = '/til'
weight = 30

[[menus.main]]
name = 'Shelf'
pageRef = '/shelf'
weight = 40

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 50
